In [119]:
import torch
import numpy as np
import torch.nn as nn
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [75]:
start_time = time.time()
#burda matrix operasyonları yap
zeros = torch.zeros(1,1)
end_time = time.time()
elapsed_time= end_time-start_time
print(f"{elapsed_time:.8f}")

0.00000000


In [83]:
torch_rand1 = torch.rand(100,100,100,100).to(device)
torch_rand2 = torch.rand(100,100,100,100).to(device)
np_rand1 = torch.rand(100,100,100,100)
np_rand2 = torch.rand(100,100,100,100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")#gpu işleminin süresi


start_time = time.time()

rand = np.multiply(np_rand1,np_rand2)
end_time = time.time()
elapsed_time=end_time-start_time
print(f"{elapsed_time:.8f}")#cpu işleminin süresi

0.06221080
0.24123263


C:\Users\Victus\AppData\Local\Temp\ipykernel_29552\3203321684.py:18: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1,np_rand2)


In [95]:
#torch.stack, torch.multinomial, torch.tril, torch.triu, input.T / input.transpose, nn.Linear, torh.cat, F.softmax(show all the examples of functions/methods with pytorch docs)

#define a probability tensor
probabilites = torch.tensor([0.1,0.9])
#%10 veya 0.1 => 0, %98 veya 0.9 => 1. each prob. points to the index of the prob in the tensor
#draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilites,num_samples = 10,replacement = True)
print(samples)


tensor([1, 1, 1, 1, 0, 1, 0, 1, 1, 1])


In [13]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-11, -69, -32,  55,  49, -64])

In [15]:
tensor = torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [17]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [28]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [32]:
linspace = torch.linspace(3,10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [40]:
logspace = torch.logspace(start = -10, end = 10,steps = 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [42]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [48]:
a = torch.empty((2,3),dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [101]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0,2.0,3.0])

softmax_output = F.softmax(tensor1,dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [125]:
vocab_size=1000
embedding_dim=100
embedding = nn.Embedding(vocab_size,embedding_dim)

input_indices = torch.LongTensor([1,5,3,2])

embedded_outputs = embedding(input_indices)

print(embedded_outputs.shape)

torch.Size([4, 100])
